learn_temp/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# Template Tagging. Always give app name as the original app name. This name will indicate in relative html file
app_name = 'basic_app'

# The name parameter will indicate to html file
urlpatterns=[
    url(r'^relative/$',views.relative,name='relative_page'),
    url(r'^other/$',views.other,name='other_page'),
]

learn_temp/learn_temp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^basic_app/',include('basic_app.urls')),
]

learn_temp/basic_app/models.py
from django.db import models

# Create your models here.

learn_temp/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    dict = {'text':'hello world', 'number':123}
    return render(request,'basic_app/index.html', dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/rltv_url_temp.html')

learn_temp/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class='navbar-brand' href="{% url 'index' %}">Brand</a></li>
          <li><a class='navbar-link' href="{% url 'admin:index'%}">Admin</a></li>
          <li><a class='navbar-link' href="{% url 'basic_app:other_page' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything Outside of this block is going to be inherited -->
      {% endblock %}
    </div>

  </body>
</html>

learn_temp/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load my_temp %}
  {% block body_block %}

    <h1>Welcome to Index</h1>
    <h1>{{ text|cut_string:'world' }}</h1>
    <h2>{{ number }}</h2>
  {% endblock %}

learn_temp/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}

    <h1>Welcome to Other</h1>
    <h2>You are now at Other Page</h2>

  {% endblock %}

learn_temp/templates/basic_app/rltv_url_temp.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to Relative URL Template</h1>
    <a href="{% url 'basic_app:other_page' %}">The Other Page</a>
    <a href="{% url 'admin:index' %}">Admin</a>
    <a href="{% url 'index' %}">Index Page</a>

  </body>
</html>